### ISSUE TITLE
DNS Issue

### ISSUE THREAD

**Issue by djeraseit** [subins2000/search#17]
Your demo site http://search.subinb.com is down.

http://search.subinsb.com/about/stats.php

**Comment by subins2000** [comment]
The site's been down cause the free hosting provided by OpenShift, RedHat has ended.

**Comment by djeraseit** [comment]
Hi Subin. I really like your software and think you are an awesome developer. Do you need help with hosting or selling software?

**Comment by subins2000** [comment]
@djeraseit Thank you ! If I get enough donations, I may host it back again 

http://subinsb.com/donate

**Comment by BasToTheMax** [comment]
> The site's been down cause the free hosting provided by OpenShift, RedHat has ended.

https://turbohost.nl/?language=english has an 1 gb free webhosting :)

**Comment by BasToTheMax** [comment]
So u could use that.
