### ISSUE TITLE
What is the password and login to access http: // localhost / crawler / admin

### ISSUE THREAD

**Issue by Yukov455** [subins2000/search#18]
I don’t know what password. Please tell me

**Comment by subins2000** [comment]
You can change the username and password by changing the hash value in `crawler/admin/index.php`. You can use [duckduckgo](https://duckduckgo.com/?q=sha512+mytexthere&t=lm&ia=answer) for getting the hash.

**Comment by Yukov455** [comment]
https://github.com/subins2000/search/blob/master/crawler/admin/index.php
Where exactly should the hash be changed?
And after that, how do I change my username and password?
Thanks in advance!

**Comment by Yukov455** [comment]
Line numbers and what needs to be changed there, you can write
