### ISSUE TITLE
How to crawl more than 1 websites?

### ISSUE THREAD

**Issue by baoc75** [subins2000/search#2]
I really like your script and I am trying to let them crawling more than 1 websites. Is this possible? And do you plan to let user submit url? Thanks :)

**Comment by subins2000** [comment]
I'm making a more advanced admin panel. Wait...

**Comment by BasToTheMax** [comment]
> I'm making a more advanced admin panel. Wait...

I created a fork, but the crawler didn't work, so I created my own crawler :)

I will add more security and then I will add a pull request to it :)

(sorry for my na English)
