### ISSUE TITLE
Admin access

### ISSUE THREAD

**Issue by SnDer** [subins2000/search#5]
What is the info for access to the admin panel?

And I keep getting issues that my irk is not correct, where do I need too put those?

**Comment by athulrajdr** [comment]
You can update the default username and password by changing the hash on **crawler/admin/index.php**

update these variables with generated hash 

`$ushahs="hash for username"`

`$hashed="hashfor password"`

You may [Generate hash from here](http://md5decrypt.net/en/Sha512/)
