### ISSUE TITLE
HOST already defined error

### ISSUE THREAD

**Issue by subins2000** [subins2000/search#8]
HOST already defined error is produced

![screen shot 2016-11-03 at 6 16 26 pm](https://cloud.githubusercontent.com/assets/2305675/19992381/45679656-a263-11e6-93c9-792dbd4fc870.png)

**Comment by athulrajdr** [comment]
the problem still persists even after the last commit  d85ec62

**Comment by subins2000** [comment]
Where do you see this bug ?

**Comment by athulrajdr** [comment]
![screenshot 8](https://cloud.githubusercontent.com/assets/7678226/20029972/604d5a04-a381-11e6-80b0-85c629667a0e.png)

HOST is defined no-where in this code

**Comment by subins2000** [comment]
Make sure you're using the latest code. HOST is defined here : https://github.com/subins2000/search/blob/master/inc/config.php#L12

**Comment by athulrajdr** [comment]
I was with and old commit. Now its fixed. Thank you
